# Generated by Django 4.2.7 on 2025-07-23 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendations', '0001_initial'),
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfoodrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfoodpreference',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.food'),
        ),
        migrations.AddField(
            model_name='userfoodpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='similarfood',
            name='food1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='nutrition.food'),
        ),
        migrations.AddField(
            model_name='similarfood',
            name='food2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_from', to='nutrition.food'),
        ),
        migrations.AddField(
            model_name='recommendationsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.food'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommendations.recommendationsession'),
        ),
        migrations.AddField(
            model_name='nutritionalprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutritional_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foodconsumption',
            name='daily_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_consumptions', to='recommendations.dailynutritionlog'),
        ),
        migrations.AddField(
            model_name='foodconsumption',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.food'),
        ),
        migrations.AddField(
            model_name='dailynutritionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userfoodrating',
            index=models.Index(fields=['user', 'rating'], name='recommendat_user_id_f0ba56_idx'),
        ),
        migrations.AddIndex(
            model_name='userfoodrating',
            index=models.Index(fields=['food', 'rating'], name='recommendat_food_id_ae6e5b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userfoodrating',
            unique_together={('user', 'food')},
        ),
        migrations.AlterUniqueTogether(
            name='userfoodpreference',
            unique_together={('user', 'food')},
        ),
        migrations.AddIndex(
            model_name='similarfood',
            index=models.Index(fields=['food1', 'overall_similarity'], name='recommendat_food1_i_799a60_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='similarfood',
            unique_together={('food1', 'food2')},
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('session', 'position')},
        ),
        migrations.AddIndex(
            model_name='dailynutritionlog',
            index=models.Index(fields=['user', 'date'], name='recommendat_user_id_f1f9c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailynutritionlog',
            unique_together={('user', 'date')},
        ),
    ]
